### ISSUE TITLE
FL TODO (5 left)

### ISSUE THREAD

**Issue by Gting6** [Urban-Research-Group/outage-data-scraper#38]
5 FL EMCs still need to be added:

- [ ] https://www.westflorida.coop/outages
- [ ] https://my.talquinelectric.com/outages/maps/ (started but was not able to get it to work, layout_10, class Scraper6)
- [ ] https://www.jea.com/outage_center/OutageMap_Reporting/
- [ ] https://fpua.com/outage-map/
- [ ] https://outagemap.talgov.com/
